export const green = '#1F901C'
export const lightGreen = '#ABE6AE'
export const yellow = '#DEA918'
export const lightYellow = '#F5E4B2'
export const blue = '#019DDE'
export const lightBlue = '#ADE1FC'
export const gray = '#6b6b6b'
export const red = '#dc4545'